# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto_files import structures_pb2 as proto__files_dot_structures__pb2


class SampleServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SampleMethod = channel.unary_unary(
                '/SampleService/SampleMethod',
                request_serializer=proto__files_dot_structures__pb2.SampleRequest.SerializeToString,
                response_deserializer=proto__files_dot_structures__pb2.SampleResponse.FromString,
                )


class SampleServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def SampleMethod(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SampleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SampleMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.SampleMethod,
                    request_deserializer=proto__files_dot_structures__pb2.SampleRequest.FromString,
                    response_serializer=proto__files_dot_structures__pb2.SampleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SampleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SampleService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def SampleMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SampleService/SampleMethod',
            proto__files_dot_structures__pb2.SampleRequest.SerializeToString,
            proto__files_dot_structures__pb2.SampleResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
